api/urls.py
from django.urls import path
from .views import CrudView,CreateForm,Todo,Detail,UpdatePlace,PersonCreateView,PersonUpdateDeleteView,delete
app_name='api'
urlpatterns = [
    # api
    path('api/',CrudView.as_view(),name='crudview'),
    path('create/', PersonCreateView.as_view()),
    path('api/<int:id>/', PersonUpdateDeleteView.as_view()),
    # 
    path('',Todo.as_view(),name='todo'),
    path('detail/<int:id>/',Detail.as_view(),name='detail'),
    path('person/',CreateForm.as_view(),name='create'),
    path('delete/<int:pk>/',delete,name='delete'),
    path('update/<int:pk>/',UpdatePlace.as_view(),name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('api.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.
class CrudModel(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    phone=models.CharField(max_length=13,null=True,blank=True)
    location=models.CharField(max_length=100,null=True,blank=True)
    hobiy=models.CharField(max_length=100,null=True,blank=True)
    body=models.TextField(null=True,blank=True)
    img=models.ImageField(upload_to='img',null=True,blank=True)
    def __str__(self) -> str:
        return self.first_name

api/forms.py
from .models import CrudModel
from django import forms

class CrudForm(forms.ModelForm):
    class Meta:
        model=CrudModel
        fields='__all__'
        

api/views.py
from django.shortcuts import render,redirect,get_object_or_404
from rest_framework.views import APIView
from django.views import View
from .serializers import CrudSerializer
from rest_framework.response import Response
from .models import CrudModel
from .forms import CrudForm
from rest_framework import status
from rest_framework import permissions
from rest_framework import generics

# from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
# Create your views here.

class PersonCreateView(APIView):
    serializer_class = CrudSerializer
    permission_classes = [permissions.AllowAny]
    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PersonUpdateDeleteView(APIView):
    serializer_class=CrudSerializer
    permission_classes = [permissions.AllowAny]
    def get(self,request,id):
        card=CrudModel.objects.get(id=id)
        serializer= CrudSerializer(instance=card)
        return Response(serializer.data)
    def post(self, request,id):
        card=CrudModel.objects.get(id=id)
        serializer = self.serializer_class(instance=card,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
          

class CrudView(APIView):
    def get_queryset(self):
        return CrudModel.objects.all()
    
    def get(self, request):
        cards = self.get_queryset()
        serializer = CrudSerializer(cards, many=True)
        return Response(serializer.data)






class CreateForm(View):
    def get(self,request):
        forms=CrudForm()
        return render(request,'forms/create.html',context={'forms':forms})
    
    def post(self,request):
        forms=CrudForm(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('api:crudview')
        return render(request,'forms/create.html',context={'forms':forms})
    
        


class Todo(View):
    def get(self,request):
        piple=CrudModel.objects.all()
        return render(request,'todo.html',context={'piple':piple})
    
class Detail(View):
    def get(self,request,id):
        person=CrudModel.objects.get(id=id)
        return render(request,'detail.html',context={'person':person})

class UpdatePlace(View):
    def get(self, request, pk):
        place_instance = get_object_or_404(CrudModel, id=pk)
        form = CrudForm(instance=place_instance)
        return render(request, 'forms/update.html', context={'forms': form})

        
    def post(self, request, pk):
        place_instance = get_object_or_404(CrudModel, id=pk)
        form = CrudForm(instance=place_instance, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('api:todo')
        return render(request, 'forms/update.html', context={'forms': form})
    
def delete(request, pk):
    place_instance = get_object_or_404(CrudModel, id=pk)
    place_instance.delete()
    return redirect('api:todo')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand text-light" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon text-light"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light">
              <li class="nav-item">
                <a class="nav-link active text-light" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item text-light" href="#">Action</a></li>
                  <li><a class="dropdown-item text-light" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider text-light"></li>
                  <li><a class="dropdown-item text-light" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled text-light" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {% block content %}
      
      {% endblock  %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1 class="mb-3 text-center">{{person.first_name}} {{person.last_name}}</h1>
        <div style="display: flex; justify-content: space-between; gap: 20px;">
            <img src="{{person.img.url}}" alt="" style="width: 400px; height: 75vh;">
            <div>
                <p style="float: right;">{{person.body|slice:1000}}</p>
                 <div>
                    <span>
                        <span style="font-weight: 900;">email:</span>
                        <i>{{person.email}}</i>
                    </span>
                    <span style="margin-left: 100px;">
                        <span style="font-weight: 900;">phone:</span>
                        <i>{{person.phone}}</i>
                    </span>
                </div>
                <div style=" margin-top:20px;">
                    <span>
                        <span style="font-weight: 900;">location:</span>
                        <i>{{person.location}}</i>
                    </span>
                    <span style="margin-left: 233px;">
                        <span style="font-weight: 900;">hobiy:</span>
                        <i>{{person.hobiy}}</i>
                    </span>
                </div>
            </div>
        </div>
       
    </div>

{% endblock  %}

templates/forms/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}CreateForm{% endblock title %}
{% block content %}
        <div class="container p-3">
            <h2 class='text-center'>Foydalanuvchi yaratish</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{forms|crispy}}
                <button class="btn btn-primary w-100 fs-5">Submit</button>
            </form>
        </div>
{% endblock  %}
    

templates/forms/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Update{% endblock title %}
{% block content %}
        <div class="container p-3">
            <h2 class='text-center'>Foydalanuvchi O'zgartirish</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{forms|crispy}}
                <button class="btn btn-primary w-100 fs-5">Submit</button>
            </form>
        </div>
{% endblock  %}
    

templates/todo.html
{% extends "base.html" %}

{% block content %}
  <div class='container mt-3'>
    <table class="table table-hover table-dark">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">First</th>
          <th scope="col">Last</th>
          <th scope="col">email</th>
          <th scope="col">phone</th>
          <th scope="col">location</th>
          <th scope="col">hobiy</th>
          <th scope="col">Amallar</th>
        </tr>
      </thead>
      <tbody>
        {% for i in piple %}
        <tr>
          <th scope="row">{{i.id}}</th>
          <td>{{i.first_name}}</td>
          <td>{{i.last_name}}</td>
          <td>{{i.email}}</td>
          <td>{{i.phone}}</td>
          <td>{{i.location}}</td>
          <td>{{i.hobiy}}</td>
          <td>
            <a href="{%url 'api:detail' i.id%}" class="btn btn-primary" style="width: 50px;font-size: 12px;text-align: center;">Ko'rish</a>
            <a href="{%url 'api:update' i.id%}" class="btn btn-warning" style="width: 80px;font-size: 12px;">O'zgartirish</a>
            <a href="{%url 'api:delete' i.id%}" class="btn btn-danger" style="width: 50px;font-size: 12px;">Delet</a>
          </td> 
        </tr>
        {% endfor %}
    </table>
  </div>
{% endblock  %}